---
title: "UCI Human Activity Recognition Using Smartphones Data Set"
author: "Rafid Sadman Eesha"
date: "5/21/2020"
output: pdf_document
---

## Codebook on the Analysis Data - Variables & Summaries 

This codebook lists down all the variables of the dataset found from running the run_analysis.R script.
The values in the columns are MEAN values generated by grouping Subject-ID and activity names. Each value represent the mean values for the respected variables.

The resultant dataset has a dimension of 180 rows and 88 columns. 

## Unique IDs 
## Unique IDs 
**Subject_ID** 				: Unique ID of the person who participated in the experiment. 
**activity_name**			: Name of the activity("Walking", "Walking-Upstairs" "Laying" etc.)

##Variables
**tBodyAcc-mean()-X**       : Body Acceleration Mean value - X axis
**tBodyAcc-mean()-Y** 		: Body Acceleration Mean value - Y axis
**tBodyAcc-mean()-Z **		: Body Acceleration Mean value - Z axis
**tBodyAcc-std()-X **		: Body Acceleration Standard Deviation value - X axis
**tBodyAcc-std()-Y **		: Body Acceleration Standard Deviation value - Y axis
**tBodyAcc-std()-Z **		: Body Acceleration Standard Deviation value - Z axis
**tGravityAcc-mean()-X**    : Gravity Acceleration Mean value - X Axis

###The rest of the variables have a similar pattern.
**tGravityAcc-mean()-Y** 	
**tGravityAcc-mean()-Z** 	
**tGravityAcc-std()-X**
**tGravityAcc-std()-Y**
**tGravityAcc-std()-Z**
**tBodyAccJerk-mean()-X**
**tBodyAccJerk-mean()-Y**
**tBodyAccJerk-mean()-Z**
**tBodyAccJerk-std()-X**
**tBodyAccJerk-std()-Y**
**tBodyAccJerk-std()-Z**
**tBodyGyro-mean()-X**
**tBodyGyro-mean()-Y**
**tBodyGyro-mean()-Z**
**tBodyGyro-std()-X**
**tBodyGyro-std()-Y**
**tBodyGyro-std()-Z**
**tBodyGyroJerk-mean()-X**
**tBodyGyroJerk-mean()-Y**
**tBodyGyroJerk-mean()-Z**
**tBodyGyroJerk-std()-X**
**tBodyGyroJerk-std()-Y**
**tBodyGyroJerk-std()-Z**
**tBodyAccMag-mean()**
**tBodyAccMag-std()**
**tGravityAccMag-mean()**
**tGravityAccMag-std()**
**tBodyAccJerkMag-mean()**
**tBodyAccJerkMag-std()**
**vtBodyGyroMag-mean()**
**tBodyGyroMag-std()**
**tBodyGyroJerkMag-mean()**
**tBodyGyroJerkMag-std()**
**fBodyAcc-mean()-X**
**fBodyAcc-mean()-Y**
**fBodyAcc-mean()-Z**
**fBodyAcc-std()-X**
**fBodyAcc-std()-Y**
**fBodyAcc-std()-Z**
**fBodyAcc-meanFreq()-X**
**fBodyAcc-meanFreq()-Y**
**fBodyAcc-meanFreq()-Z**
**fBodyAccJerk-mean()-X**
**fBodyAccJerk-mean()-Y**
**fBodyAccJerk-mean()-Z**
**fBodyAccJerk-std()-X**
**fBodyAccJerk-std()-Y**
**fBodyAccJerk-std()-Z**
**fBodyAccJerk-meanFreq()-X**
**fBodyAccJerk-meanFreq()-Y**
**fBodyAccJerk-meanFreq()-Z**
**fBodyGyro-mean()-X**
**fBodyGyro-mean()-Y**
**fBodyGyro-mean()-Z**
**fBodyGyro-std()-X**
**fBodyGyro-std()-Y**
**fBodyGyro-std()-Z**
**fBodyGyro-meanFreq()-X**
**fBodyGyro-meanFreq()-Y**
**fBodyGyro-meanFreq()-Z**
**fBodyAccMag-mean()**
**fBodyAccMag-std()**
**fBodyAccMag-meanFreq()**
**fBodyBodyAccJerkMag-mean()**
**fBodyBodyAccJerkMag-std()**
**fBodyBodyAccJerkMag-meanFreq()**
**fBodyBodyGyroMag-mean()**
**fBodyBodyGyroMag-std()**
**fBodyBodyGyroMag-meanFreq()**
**fBodyBodyGyroJerkMag-mean()**
**fBodyBodyGyroJerkMag-std()**
**fBodyBodyGyroJerkMag-meanFreq()**
**angle(tBodyAccMean,gravity)**
**angle(tBodyAccJerkMean),gravityMean)**
**angle(tBodyGyroMean,gravityMean)**
**angle(tBodyGyroJerkMean,gravityMean)**
**angle(X,gravityMean)**
**angle(Y,gravityMean)**
**angle(Z,gravityMean)**
